irerp_application_dashboard:
    resource: "@IrErpApplicationDashboardBundle/Resources/config/routing.yml"
    prefix:   /
    
irerp_application_user_security:
    resource: "@IrErpApplicationUserBundle/Resources/config/routing/security.yml"
    
irerp_application_user_my_account:
    resource: "@IrErpApplicationUserBundle/Resources/config/routing/my_account.yml"
    prefix:  /my-account/
    
irerp_application_user_user:    
    resource: "@IrErpApplicationUserBundle/Resources/config/routing/user.yml"
    prefix:   /configuration/users/

irerp_application_general_country:
    resource: "@IrErpApplicationGeneralBundle/Resources/config/routing/country.yml"
    prefix:  /general/countries/